### ISSUE TITLE
project com.oracle.truffle.api.dsl was removed as JDK 1.8 is not available

### ISSUE THREAD

**Issue by fniephaus** [graalvm/mx#150]
My JDK9-based CI builds running mx `5.172.0` are failing because various projects are "removed as JDK 1.8 is not available". AFAICT related changes were introduced with https://github.com/graalvm/mx/commit/1c4adb1e3a6ca813ff4a693c7fcc7b48bb1b3085 and it seems the problem is that Graal's and Truffle's suite.py haven't been updated yet (e.g. with `"javaCompliance" : "1.8+"`). I have been running CI builds for around 6 months, this is the first time a new version of mx has caused build failures. Locking the mx version until this has been resolved...

**Comment by dougxc** [comment]
Graal and Truffle's suite.py will probably not be updated. At least, not all projects since some of them use JDK 8 internal API and hence now *require* a JDK 8 to build. For more background on this change, see http://mail.openjdk.java.net/pipermail/graal-dev/2018-June/005410.html. Sorry for the inconvenience but this change was necessary as we start to work on supporting SVM on JDK 11.

**Comment by dougxc** [comment]
Feel free to re-open (or reply to mail on graal-dev list) if you have further questions.

**Comment by fniephaus** [comment]
Thanks for the update!
