### ISSUE TITLE
Make `_stage_file_impl` handle both files and directories

### ISSUE THREAD

**Issue by petermz** [graalvm/mx#258]
`_stage_file_impl` calls `shutil.copy` which can only copy files:
https://github.com/graalvm/mx/blob/39ac3b71912af1edf04f7413adf36a74550c09bb/mx_jardistribution.py#L1437

But AFAICT it is expected to copy directories too, see e.g.:
https://github.com/graalvm/mx/blob/39ac3b71912af1edf04f7413adf36a74550c09bb/mx.py#L7680

I'm not sure how this works for everyone else; for me it fails on Windows very quickly.

**Comment by dougxc** [comment]
The underlying problem here is that the support for Windows is not well tested when Windows is running in non-developer mode and thus [does not support proper symlinks](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/).
I propose that instead of continuing to try support this, we just make it a requirement for Windows to be in developer mode to use mx.
Not being a Windows user, I always forget how exactly to put Windows into developer mode but I'm sure our in-house expert @pejovica can help here.
